name: rs_seek
description: A modern and complete Flutter package for building responsive UIs across mobile, tablet, and desktop with orientation support.
version: 1.0.0
homepage: https://github.com/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
